# This is a basic workflow to help you get started with Actions

name: Create .env file for main

# Controls when the action will run.
# Triggers the workflow on push or pull request events
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_env_file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
    - name: create-env
      run: |
        echo '${{ secrets.ENV_FILE }}' > '.env'
      working-directory: ${{ env.working-directory }}
